---
name: Application List
type: app
attributes:
  - model_name: entries
    type: List
    description: List of entries
    attributes:
      - model_name: app
        tf_name: application
        type: String
        description: Application name
        example: netflix
      - model_name: appFamily
        tf_name: application_family
        type: String
        description: Application family name
        example: web
