// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanDeviceACLPolicyDefinition(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanDeviceACLPolicyDefinitionConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "default_action", "drop"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.id", "10"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.ip_type", "ipv4"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.name", "Sequence 10"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.base_action", "accept"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.match_entries.0.type", "destinationPort"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.match_entries.0.destination_port", "22"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.action_entries.0.type", "count"),
					resource.TestCheckResourceAttr("data.sdwan_device_acl_policy_definition.test", "sequences.0.action_entries.0.counter_name", "count1"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanDeviceACLPolicyDefinitionConfig = `

resource "sdwan_device_acl_policy_definition" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  default_action = "drop"
  sequences = [{
    id = 10
    ip_type = "ipv4"
    name = "Sequence 10"
    base_action = "accept"
	match_entries = [{
		type = "destinationPort"
		destination_port = 22
	}]
	action_entries = [{
		type = "count"
		counter_name = "count1"
	}]
  }]
}

data "sdwan_device_acl_policy_definition" "test" {
  id = sdwan_device_acl_policy_definition.test.id
}
`
