// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanPolicerPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanPolicerPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_policer_policy_object.test", "entries.0.burst", "100000"),
					resource.TestCheckResourceAttr("data.sdwan_policer_policy_object.test", "entries.0.exceed_action", "remark"),
					resource.TestCheckResourceAttr("data.sdwan_policer_policy_object.test", "entries.0.rate", "100"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanPolicerPolicyObjectConfig = `

resource "sdwan_policer_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    burst = 100000
    exceed_action = "remark"
    rate = 100
  }]
}

data "sdwan_policer_policy_object" "test" {
  id = sdwan_policer_policy_object.test.id
}
`
