// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-sdwan"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource              = &SLAClassPolicyObjectDataSource{}
	_ datasource.DataSourceWithConfigure = &SLAClassPolicyObjectDataSource{}
)

func NewSLAClassPolicyObjectDataSource() datasource.DataSource {
	return &SLAClassPolicyObjectDataSource{}
}

type SLAClassPolicyObjectDataSource struct {
	client *sdwan.Client
}

func (d *SLAClassPolicyObjectDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sla_class_policy_object"
}

func (d *SLAClassPolicyObjectDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "This data source can read the SLA Class policy object.",

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "The id of the policy object",
				Required:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the policy object",
				Computed:            true,
			},
			"entries": schema.ListNestedAttribute{
				MarkdownDescription: "List of entries",
				Computed:            true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_probe_class_id": schema.StringAttribute{
							MarkdownDescription: "App Probe Class Policy Object ID",
							Computed:            true,
						},
						"jitter": schema.Int64Attribute{
							MarkdownDescription: "Jitter in ms",
							Computed:            true,
						},
						"latency": schema.Int64Attribute{
							MarkdownDescription: "Latency in ms",
							Computed:            true,
						},
						"loss": schema.Int64Attribute{
							MarkdownDescription: "Loss in percent",
							Computed:            true,
						},
						"fallback_best_tunnel_criteria": schema.StringAttribute{
							MarkdownDescription: "",
							Computed:            true,
						},
						"fallback_best_tunnel_jitter": schema.Int64Attribute{
							MarkdownDescription: "Jitter variance in ms",
							Computed:            true,
						},
						"fallback_best_tunnel_latency": schema.Int64Attribute{
							MarkdownDescription: "Latency variance in ms",
							Computed:            true,
						},
						"fallback_best_tunnel_loss": schema.Int64Attribute{
							MarkdownDescription: "Loss variance in percent",
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (d *SLAClassPolicyObjectDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, _ *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	d.client = req.ProviderData.(*sdwan.Client)
}

func (d *SLAClassPolicyObjectDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config SLAClass

	// Read config
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("%s: Beginning Read", config.Id.String()))

	res, err := d.client.Get("/template/policy/list/sla/" + config.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Failed to retrieve object, got error: %s", err))
		return
	}

	config.fromBody(ctx, res)

	tflog.Debug(ctx, fmt.Sprintf("%s: Read finished successfully", config.Id.ValueString()))

	diags = resp.State.Set(ctx, &config)
	resp.Diagnostics.Append(diags...)
}
