//go:build testAll

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanRegionListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanRegionListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_region_list_policy_object.test", "entries.0.region_id", "1-2"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanRegionListPolicyObjectConfig = `

resource "sdwan_region_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    region_id = "1-2"
  }]
}

data "sdwan_region_list_policy_object" "test" {
  id = sdwan_region_list_policy_object.test.id
}
`
