// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanCiscoBannerFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanCiscoBannerFeatureTemplateConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_cisco_banner_feature_template.test", "login", "My Login Banner"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_banner_feature_template.test", "motd", "My MOTD Banner"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanCiscoBannerFeatureTemplateConfig = `

resource "sdwan_cisco_banner_feature_template" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  device_types = ["vedge-C8000V"]
  login = "My Login Banner"
  motd = "My MOTD Banner"
}

data "sdwan_cisco_banner_feature_template" "test" {
  id = sdwan_cisco_banner_feature_template.test.id
}
`
