// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanVPNListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanVPNListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_vpn_list_policy_object.test", "entries.0.vpn_id", "100-200"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanVPNListPolicyObjectConfig = `

resource "sdwan_vpn_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    vpn_id = "100-200"
  }]
}

data "sdwan_vpn_list_policy_object" "test" {
  id = sdwan_vpn_list_policy_object.test.id
}
`
