// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanExtendedCommunityListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanExtendedCommunityListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_extended_community_list_policy_object.test", "entries.0.community", "community rt 100:10"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanExtendedCommunityListPolicyObjectConfig = `

resource "sdwan_extended_community_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    community = "community rt 100:10"
  }]
}

data "sdwan_extended_community_list_policy_object" "test" {
  id = sdwan_extended_community_list_policy_object.test.id
}
`
