// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanSiteListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanSiteListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_site_list_policy_object.test", "entries.0.site_id", "100-200"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanSiteListPolicyObjectConfig = `

resource "sdwan_site_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    site_id = "100-200"
  }]
}

data "sdwan_site_list_policy_object" "test" {
  id = sdwan_site_list_policy_object.test.id
}
`
