// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanCLITemplateFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanCLITemplateFeatureTemplateConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_cli_template_feature_template.test", "cli_config", "! Enable new BGP community format\nip bgp-community new-format\n"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanCLITemplateFeatureTemplateConfig = `

resource "sdwan_cli_template_feature_template" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  device_types = ["vedge-C8000V"]
  cli_config = "! Enable new BGP community format\nip bgp-community new-format\n"
}

data "sdwan_cli_template_feature_template" "test" {
  id = sdwan_cli_template_feature_template.test.id
}
`
