// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanClassMapPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanClassMapPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_class_map_policy_object.test", "entries.0.queue", "2"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanClassMapPolicyObjectConfig = `

resource "sdwan_class_map_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    queue = 2
  }]
}

data "sdwan_class_map_policy_object" "test" {
  id = sdwan_class_map_policy_object.test.id
}
`
