// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanASPathListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanASPathListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_as_path_list_policy_object.test", "entries.0.as_path", "^1239_[0-9]*$"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanASPathListPolicyObjectConfig = `

resource "sdwan_as_path_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    as_path = "^1239_[0-9]*$"
  }]
}

data "sdwan_as_path_list_policy_object" "test" {
  id = sdwan_as_path_list_policy_object.test.id
}
`
