// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanCiscoBFDFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanCiscoBFDFeatureTemplateConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "multiplier", "3"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "poll_interval", "800000"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "default_dscp", "48"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "colors.0.color", "private5"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "colors.0.hello_interval", "1000"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "colors.0.multiplier", "7"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "colors.0.pmtu_discovery", "true"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_bfd_feature_template.test", "colors.0.dscp", "46"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanCiscoBFDFeatureTemplateConfig = `

resource "sdwan_cisco_bfd_feature_template" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  device_types = ["vedge-C8000V"]
  multiplier = 3
  poll_interval = 800000
  default_dscp = 48
  colors = [{
    color = "private5"
    hello_interval = 1000
    multiplier = 7
    pmtu_discovery = true
    dscp = 46
  }]
}

data "sdwan_cisco_bfd_feature_template" "test" {
  id = sdwan_cisco_bfd_feature_template.test.id
}
`
