// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanCiscoThousandEyesFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanCiscoThousandEyesFeatureTemplateConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.instance_id", "1"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.application_type", "te"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_account_group_token", "1234567"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_vpn", "1"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_agent_ip", "1.1.1.2/24"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_default_gateway", "1.1.1.255"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_name_server", "10.2.2.2"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_hostname", "agent1"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_web_proxy_type", "static"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_proxy_host", "3.3.3.3"),
					resource.TestCheckResourceAttr("data.sdwan_cisco_thousandeyes_feature_template.test", "virtual_applications.0.te_proxy_port", "80"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanCiscoThousandEyesFeatureTemplateConfig = `

resource "sdwan_cisco_thousandeyes_feature_template" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  device_types = ["vedge-C8000V"]
  virtual_applications = [{
    instance_id = "1"
    application_type = "te"
    te_account_group_token = "1234567"
    te_vpn = 1
    te_agent_ip = "1.1.1.2/24"
    te_default_gateway = "1.1.1.255"
    te_name_server = "10.2.2.2"
    te_hostname = "agent1"
    te_web_proxy_type = "static"
    te_proxy_host = "3.3.3.3"
    te_proxy_port = 80
  }]
}

data "sdwan_cisco_thousandeyes_feature_template" "test" {
  id = sdwan_cisco_thousandeyes_feature_template.test.id
}
`
