// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceSdwanApplicationListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanApplicationListPolicyObjectConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_application_list_policy_object.test", "entries.0.application", "netflix"),
					resource.TestCheckResourceAttr("data.sdwan_application_list_policy_object.test", "entries.0.application_family", "web"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanApplicationListPolicyObjectConfig = `

resource "sdwan_application_list_policy_object" "test" {
  name = "TF_TEST_MIN"
  entries = [{
    application = "netflix"
    application_family = "web"
  }]
}

data "sdwan_application_list_policy_object" "test" {
  id = sdwan_application_list_policy_object.test.id
}
`
