// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type RegionList struct {
	Id      types.String        `tfsdk:"id"`
	Name    types.String        `tfsdk:"name"`
	Entries []RegionListEntries `tfsdk:"entries"`
}

type RegionListEntries struct {
	RegionId types.String `tfsdk:"region_id"`
}

func (data RegionList) getType() string {
	return "region"
}

func (data RegionList) toBody(ctx context.Context) string {
	body, _ := sjson.Set("", "description", "Desc Not Required")
	body, _ = sjson.Set(body, "name", data.Name.ValueString())
	body, _ = sjson.Set(body, "type", "region")
	if len(data.Entries) > 0 {
		body, _ = sjson.Set(body, "entries", []interface{}{})
		for _, item := range data.Entries {
			itemBody := ""
			if !item.RegionId.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "regionId", item.RegionId.ValueString())
			}
			body, _ = sjson.SetRaw(body, "entries.-1", itemBody)
		}
	}
	return body
}

func (data *RegionList) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("entries"); value.Exists() {
		data.Entries = make([]RegionListEntries, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := RegionListEntries{}
			if cValue := v.Get("regionId"); cValue.Exists() {
				item.RegionId = types.StringValue(cValue.String())
			} else {
				item.RegionId = types.StringNull()
			}
			data.Entries = append(data.Entries, item)
			return true
		})
	}
}
