// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type ASPathList struct {
	Id      types.String        `tfsdk:"id"`
	Name    types.String        `tfsdk:"name"`
	Entries []ASPathListEntries `tfsdk:"entries"`
}

type ASPathListEntries struct {
	AsPath types.String `tfsdk:"as_path"`
}

func (data ASPathList) getType() string {
	return "aspath"
}

func (data ASPathList) toBody(ctx context.Context) string {
	body, _ := sjson.Set("", "description", "Desc Not Required")
	body, _ = sjson.Set(body, "name", data.Name.ValueString())
	body, _ = sjson.Set(body, "type", "aspath")
	if len(data.Entries) > 0 {
		body, _ = sjson.Set(body, "entries", []interface{}{})
		for _, item := range data.Entries {
			itemBody := ""
			itemBody, _ = sjson.Set(itemBody, "asPath", fmt.Sprint(item.AsPath.ValueString()))
			body, _ = sjson.SetRaw(body, "entries.-1", itemBody)
		}
	}
	return body
}

func (data *ASPathList) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("entries"); value.Exists() {
		data.Entries = make([]ASPathListEntries, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ASPathListEntries{}
			if cValue := v.Get("asPath"); cValue.Exists() {
				item.AsPath = types.StringValue(cValue.String())
			} else {
				item.AsPath = types.StringNull()
			}
			data.Entries = append(data.Entries, item)
			return true
		})
	}
}
