// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type ApplicationList struct {
	Id      types.String             `tfsdk:"id"`
	Name    types.String             `tfsdk:"name"`
	Entries []ApplicationListEntries `tfsdk:"entries"`
}

type ApplicationListEntries struct {
	Application       types.String `tfsdk:"application"`
	ApplicationFamily types.String `tfsdk:"application_family"`
}

func (data ApplicationList) getType() string {
	return "app"
}

func (data ApplicationList) toBody(ctx context.Context) string {
	body, _ := sjson.Set("", "description", "Desc Not Required")
	body, _ = sjson.Set(body, "name", data.Name.ValueString())
	body, _ = sjson.Set(body, "type", "app")
	if len(data.Entries) > 0 {
		body, _ = sjson.Set(body, "entries", []interface{}{})
		for _, item := range data.Entries {
			itemBody := ""
			itemBody, _ = sjson.Set(itemBody, "app", fmt.Sprint(item.Application.ValueString()))
			itemBody, _ = sjson.Set(itemBody, "appFamily", fmt.Sprint(item.ApplicationFamily.ValueString()))
			body, _ = sjson.SetRaw(body, "entries.-1", itemBody)
		}
	}
	return body
}

func (data *ApplicationList) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("entries"); value.Exists() {
		data.Entries = make([]ApplicationListEntries, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := ApplicationListEntries{}
			if cValue := v.Get("app"); cValue.Exists() {
				item.Application = types.StringValue(cValue.String())
			} else {
				item.Application = types.StringNull()
			}
			if cValue := v.Get("appFamily"); cValue.Exists() {
				item.ApplicationFamily = types.StringValue(cValue.String())
			} else {
				item.ApplicationFamily = types.StringNull()
			}
			data.Entries = append(data.Entries, item)
			return true
		})
	}
}
