// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanCiscoBannerFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanCiscoBannerFeatureTemplateConfig_minimum(),
				Check:  resource.ComposeTestCheckFunc(),
			},
			{
				Config: testAccSdwanCiscoBannerFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_cisco_banner_feature_template.test", "login", "My Login Banner"),
					resource.TestCheckResourceAttr("sdwan_cisco_banner_feature_template.test", "motd", "My MOTD Banner"),
				),
			},
		},
	})
}

func testAccSdwanCiscoBannerFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_cisco_banner_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
	}
	`
}

func testAccSdwanCiscoBannerFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_cisco_banner_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		login = "My Login Banner"
		motd = "My MOTD Banner"
	}
	`
}
