// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanMirrorPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanMirrorPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_mirror_policy_object.test", "entries.0.remote_destination_ip", "10.1.1.1"),
					resource.TestCheckResourceAttr("sdwan_mirror_policy_object.test", "entries.0.source_ip", "10.2.1.1"),
				),
			},
		},
	})
}

func testAccSdwanMirrorPolicyObjectConfig_all() string {
	return `
	resource "sdwan_mirror_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			remote_destination_ip = "10.1.1.1"
			source_ip = "10.2.1.1"
		}]
	}
	`
}
