// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanASPathListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanASPathListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_as_path_list_policy_object.test", "entries.0.as_path", "^1239_[0-9]*$"),
				),
			},
		},
	})
}

func testAccSdwanASPathListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_as_path_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			as_path = "^1239_[0-9]*$"
		}]
	}
	`
}
