// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSdwanIPv4PrefixListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanIPv4PrefixListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_ipv4_prefix_list_policy_object.test", "entries.0.prefix", "10.0.0.0/12"),
					resource.TestCheckResourceAttr("sdwan_ipv4_prefix_list_policy_object.test", "entries.0.le", "32"),
					resource.TestCheckResourceAttr("sdwan_ipv4_prefix_list_policy_object.test", "entries.0.ge", "24"),
				),
			},
		},
	})
}

func testAccSdwanIPv4PrefixListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_ipv4_prefix_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			prefix = "10.0.0.0/12"
			le = 32
			ge = 24
		}]
	}
	`
}
