//go:build testAll

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanRegionListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanRegionListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_region_list_policy_object.test", "entries.0.region_id", "1-2"),
				),
			},
		},
	})
}

func testAccSdwanRegionListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_region_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			region_id = "1-2"
		}]
	}
	`
}
