// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSdwanAppProbeClassPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanAppProbeClassPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_app_probe_class_policy_object.test", "entries.0.forwarding_class", "FC1"),
					resource.TestCheckResourceAttr("sdwan_app_probe_class_policy_object.test", "entries.0.mappings.0.color", "blue"),
					resource.TestCheckResourceAttr("sdwan_app_probe_class_policy_object.test", "entries.0.mappings.0.dscp", "8"),
				),
			},
		},
	})
}

func testAccSdwanAppProbeClassPolicyObjectConfig_all() string {
	return `
	resource "sdwan_app_probe_class_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			forwarding_class = "FC1"
			mappings = [{
				color = "blue"
				dscp = 8
			}]
		}]
	}
	`
}
