// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSdwanStandardCommunityListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanStandardCommunityListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_standard_community_list_policy_object.test", "entries.0.community", "100:1000"),
				),
			},
		},
	})
}

func testAccSdwanStandardCommunityListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_standard_community_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			community = "100:1000"
		}]
	}
	`
}
