// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSdwanExtendedCommunityListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanExtendedCommunityListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_extended_community_list_policy_object.test", "entries.0.community", "community rt 100:10"),
				),
			},
		},
	})
}

func testAccSdwanExtendedCommunityListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_extended_community_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			community = "community rt 100:10"
		}]
	}
	`
}
