// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanColorListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanColorListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_color_list_policy_object.test", "entries.0.color", "blue"),
				),
			},
		},
	})
}

func testAccSdwanColorListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_color_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			color = "blue"
		}]
	}
	`
}
