// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccSdwanDataIPv6PrefixListPolicyObject(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanDataIPv6PrefixListPolicyObjectConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_data_ipv6_prefix_list_policy_object.test", "entries.0.prefix", "2001:0:0:1::/64"),
				),
			},
		},
	})
}

func testAccSdwanDataIPv6PrefixListPolicyObjectConfig_all() string {
	return `
	resource "sdwan_data_ipv6_prefix_list_policy_object" "test" {
		name = "TF_TEST_ALL"
		entries = [{
			prefix = "2001:0:0:1::/64"
		}]
	}
	`
}
